# Generated by Django 4.0.3 on 2022-05-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиента(-ов/-ы)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории(-й)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Блюдо')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredient_list', models.TextField(verbose_name='Ингредиенты')),
                ('recipe', models.TextField(null=True, verbose_name='Рецепт')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ingredients', models.ManyToManyField(to='dish.ingredient')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dish.type', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюд(-а)',
                'ordering': ['-published'],
            },
        ),
    ]
