# Generated by Django 4.0.3 on 2022-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_remove_dish_ingredient_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Блюдо'),
        ),
    ]
