# Generated by Django 4.0.3 on 2022-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_dish_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
    ]
