# Generated by Django 4.0.3 on 2022-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_like_remove_dish_likes_dish_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='like',
        ),
        migrations.AddField(
            model_name='dish',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
