# Generated by Django 4.0.3 on 2022-05-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0009_dish_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='user_likes',
            field=models.TextField(default='', null=True),
        ),
    ]
