# Generated by Django 4.0.3 on 2022-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0011_alter_dish_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='user_likes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
