# Generated by Django 4.0.3 on 2022-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0012_alter_dish_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='dish.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
