# Generated by Django 4.0.3 on 2022-05-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0013_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
