# Generated by Django 4.0.3 on 2022-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0015_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, height_field=450, null=True, upload_to='images/', verbose_name='Картинка', width_field=580),
        ),
    ]
