# Generated by Django 4.0.3 on 2022-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0017_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
